#!/bin/python3

import sys

n = int(input().strip())
a = list(map(int, input().strip().split(' ')))
# Write Your Code Here 
numSwaps = 0
for i in range (n):
    # Track number of elements swapped during a single array traversal
    currentSwaps = 0
    for j in range (0,n - 1):
        
        # Swap adjacent elements if they are in decreasing order
        if (a[j] > a[j + 1]) :
            a[j], a[j + 1] = a[j + 1] , a[j]
            currentSwaps+=1
    numSwaps += currentSwaps
    #i = i+1
    
    # # If no elements were swapped during a traversal, array is sorted
    if currentSwaps == 0 :
        break;
    
print("Array is sorted in" ,numSwaps,"swaps.")
print("First Element:",a[0])
print("Last Element:",a[-1])
    
