#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))
    a =  arr[::-1]
    listToStr = ' '.join(map(str, a)) 
    print(listToStr)  
